# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xn--kCLyP-fs7sYJAQLznkKgRh_q3LnJ
"""

import pandas as pd
import json

import numpy as np

import time
from pprint import pprint
import json
from pandas import json_normalize

#from google.colab import drive


# Commented out IPython magic to ensure Python compatibility.

# File loading
# drive.mount('/content/drive/')
# %cp -av "/content/drive/MyDrive/Colab Notebooks/# Data/location_history.json" "/content/"

# Opening JSON file
f = open('location_history.json',)

# returns JSON object as
# a dictionary
data = json.load(f)
data = data["Location History"]

len(data)
'''
def focus_Date(text):
    text = text[:-13]
    return text


def focus_heure(text):
    text = text[11:-4]
    return text


def recup_lon(o):
    o = o[:-37]
    return o


def recup_lat(o):
    o = o[23:-15]
    return o


list = [[], [], [], []]
i = 0

for period in data:
    i += 1
    list[0].append(recup_lon(period["Latitude, Longitude"]))
    list[1].append(recup_lat(period["Latitude, Longitude"]))
    list[2].append(focus_Date(period["Time"]))
    list[3].append(focus_heure(period["Time"]))
    

df = pd.DataFrame(list)
df = df.T
df.columns = ['lon', 'lat', 'Date', 'Time']

df.describe

df.to_csv(r'Path where you want to store the exported CSV file\File Name.csv')

 df['DateTime'] = df['DateTime'].apply(
    lambda _: datetime.strptime(_, "%Y-%m-%d %H:%M:%S"))
  
  for i in range(0, 4868):
      df['DateTime'].loc[i] = int((((df['DateTime'].loc[i].timestamp() - (2021-1970)*365*24*60*60)/60)/60) % 24)
'''
